### ISSUE TITLE
Module 6, Exercise 1, Task 2, Step 5 - Solution Explorer is hidden

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#19]
The Solution Explorer sidebar is hidden by default on the course VM images. So students cannot find "Lab Exercise 1.sql" script. Suggest adding instructions to enable Solution Explorer window, or even easier, open the same script in Notepad.

Same applies to all other labs that use SSMS.

**Comment by AndyFogg** [comment]
Thanks for your comments.

I have added an additional step with the instructions on how to open Solution Explorer.
