### ISSUE TITLE
"Classroom Materials" section in Readme needs to be updated

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#2]
Current text:

"To address general comments about the course & demos or how to prepare for 20778, please use the MCT forums at https://borntolearn.mslearn.net/mct/general/f/225. This is the MCT Readiness forum for discussions, news, etc. to help you prepare to teach courses and let you collaborate with other instructors."

Issues:

1) Link is incorrect
2) Is the intent to guide MCTs to MCT Support forum? If so, it's unrelated to MCT Readiness (no such forum exists).

**Comment by rootsmusic** [comment]
(I can't correct courseware.)  The MOC forum has moved to https://trainingsupport.microsoft.com/en-us/tcmct/forum/tcmct_moc

**Comment by vitaly-livshits** [comment]
It's not courseware. It's this repo. 

Link: https://github.com/MicrosoftLearning/20778-Analyzing-Data-with-Power-BI/blob/master/README.md

![image](https://user-images.githubusercontent.com/1765732/59557275-7f518180-8fa3-11e9-834a-0e4731d22790.png)

**Comment by AndyFogg** [comment]
Closed as fixed already
