### ISSUE TITLE
Lab 3, Exercise 1 Excel Import only imports one worksheet - Sales

### ISSUE THREAD

**Issue by joel-rosenblum** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#20]
In Lab 3, Exercise 1, Task 2, Step 49, I had to save the Excel Workbook under a different name since the filename Adventure Works Data in the D:\Lab3\Starter folder is read-only. Then, in Task 3, step 7 only the Sales worksheet is imported and appears in the Fields pane. The remaining worksheets do not import.

**Comment by AndyFogg** [comment]
Thanks for your comments.

The first point about the file being Read-Only, is a error when setting up the Allfiles. In the **README.md** file, step 3 gives the instructions to remove the Read-only attribute on all of the files.

The second point I am unable to replicate as all 4 worksheets have imported. On Task 3 > Step 6 there was a minor error in the text (which has now been fixed) which said _under **DATASETS**, click **Adventure Works Data**_, but this wouldn't have been available as only the **Adventure Works Sales** spreadsheet was uploaded.

**Comment by markfitzqa** [comment]
Joel-Rosenblum - the error in task 3 step 7 was present in the original VM as someone had added the Sales table into the powerpivot within the Excel worksheet.  When the worksheet is imported only the powerpivot model is seen by the import and only the Sales table uploads.  To fix this edit the Excel worksheet, go into the PowerPivot (edit model) and delete the Sales table.  The import will now import all four tables.  The tables do not have any relationships between them.

Fitz
