### ISSUE TITLE
Module 7 lab - updating data source credentials in Power BI Service

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#27]
There are two items to update:

1. Due to a bug in Power BI Service, clicking the update credentials button on the report page brings students to a "null" error page. Students should be directed to go to Settings => Data Sets => Data Set Name => Edit Credentials. The later link works fine.

1. Students should be directed to deselect the "OAuth2" checkbox at the bottom of the credentials editing screen. It seems to be enabled by default, at least on some accounts. 

![image](https://user-images.githubusercontent.com/1765732/73113587-a3365780-3ee2-11ea-8f7d-2fb76f61788c.png)

**Comment by AndyFogg** [comment]
Thank you for your comments, I am looking into them.

**Comment by AndyFogg** [comment]
These issues have been addressed in the **20778C_LAB_07_LAK.md** as follows:

1. Steps altered to access through the **Settings** menu.

1. Added step so students ensure the check box is clear.
