### ISSUE TITLE
Links with spaces broken in instruction files

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#4]
Example: https://github.com/MicrosoftLearning/20778-Analyzing-Data-with-Power-BI/blob/master/Instructions/20778C_LAB_01.md

![image](https://user-images.githubusercontent.com/1765732/59557255-07835700-8fa3-11e9-97e5-5b4e1274fbe9.png)

**Comment by AndyFogg** [comment]
Updated necessary files.
