### ISSUE TITLE
Module 3 lab is broken

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#7]
The lab in Lesson 1 does not work due to the presence of a Power Pivot model. The Power Pivot model takes precedence during upload to Power BI service, so all the worksheets (and changes to them made during the lab) are disregarded. The model is not used in the lab and should be removed from the source Excel file.

**Comment by AndyFogg** [comment]
It was opening the incorrect XLSX file, change to open the correct one.

**Comment by HappymediaDz** [comment]
I have the same issue for the same Reason.
The exercice 01 task 02 and 03 is manipulating the same file "Adventure Works Data.xlsx" and it contains a model with just one table, the sales one and as vitaly said the model take precedence so model should be removed from the source

**Comment by vitaly-livshits** [comment]
@HappymediaDz, are you using the new instructions that @AndyFogg updated? They reference a different file, "Adventure Works Sales.xlsx". That file is without a Power Pivot model, so it should work fine with Power BI Service.

**Comment by HappymediaDz** [comment]
Thank you @vitaly-livshits the content of the version I'm using is outdated but what I do not understand is that I downloaded the content on 07/14/19 and last updated was 17 days from today.
Anyway, thank you again
