### ISSUE TITLE
LAB 01 which country has the most male customer

### ISSUE THREAD

**Issue by HappymediaDz** [MicrosoftLearning/20778-Analyzing-Data-with-Power-BI#9]
Because no transformation are made to the data imported in the exercice 02 of the lab, the step (09) in the LAB_01_LAK need an extra step to guide students to replace "male" with "m", in the question, by cliking on "male" and selecting "M (DimCustomer > Gender)" in the list. Otherwase the result is a bar chart with just two bars.

**Comment by AndyFogg** [comment]
The gender is irrelevant, so removing it.
